### ISSUE TITLE
Online link to personal portfolio

### ISSUE THREAD

**Issue by Felix45** [Felix45/portfolio#6]
# GitHub pages link to personal portfolio website
[https://felix45.github.io/portfolio/](https://felix45.github.io/portfolio/)

I had deployed the application earlier that's why I submitted an issue link as per project requirements.

**Comment by rustam-tolipov** [comment]
- [ ] [OPTIONAL] Good job Felix. Please add a screenshot of your portfolio to the readme.MD file 👍
- [ ] [OPTIONAL] Let's also add missing MIT license file to your repo 📃

**Comment by rustam-tolipov** [comment]
## Hi @Felix45 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Felix45** [comment]
## Hi @Rustamxon7 

This feedback is well received and has been implemented
